name: Shell Commands

on:
  push:
    branches:
      - main
jobs:
  terraform-init-fmt-validate-plan:
    runs-on: ubuntu-latest
    container:
      image: mrtnsgs/terraform-aws:1.0
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setting up aws credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.4
      - name: Run terraform init
        run: |
          pwd ; ls -alh
          terraform init -backend=true -backend-config="backend.hcl"
      - name: Run Terraform fmt
        run: terraform fmt -recursive
      - name: Terraform validate
        run: terraform validate
      - name: Run Terraform plan and generate
        run: terraform plan -no-color
        continue-on-error: true
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
